name = "Hugoplate_modified"
license = "MIT"
licenselink = "https://github.com/mbrejla/hugoplate_modified/blob/main/LICENSE"
description = "Forked version of Hugoplate, a free starter template built with Hugo and TailwindCSS."
homepage = "https://github.com/mbrejla/hugoplate-modified"
demosite = ""
min_version = "0.121.2"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Zeon Studio & Markus Brejla"
homepage = "https://github.com/mbrejla/"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
